Rename timeout to arm cycles
AxFoundation/redax pull request #31
Opened 2021-03-09 10:19 UTC by petergaemers

Rename the references from timouts to arm cycles, since thats what we're tracking

2021-03-09 10:30 UTC, darrylmasson requested changes

2021-03-09 10:30 UTC, darrylmasson commented on dispatcher/config.ini
> +MaxArmCycles=3
This should also get added to the TESTING block

2021-03-09 15:47 UTC, darrylmasson commented on dispatcher/config.ini
> -MaxTimeout=3
> This should also get added to the TESTING block

The key word being "also"

2021-03-10 08:11 UTC, petergaemers commented on dispatcher/config.ini
> -MaxTimeout=3
Details are not my friends...

2021-03-10 10:15 UTC, darrylmasson approved these changes
I like it

2021-03-10 10:35 UTC, merged